version: '3.8'
services: 
    apache-webserver:
      image: httpd:2.4-alpine
      ports:
        - "80:80"
      volumes:
        - ../../:/usr/local/apache2/htdocs/
    nginx-webserver:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ../../:/www
            - ./config/site.conf:/etc/nginx/conf.d/default.conf:ro
    php-backend:
        image: php:7.4-fpm-alpine
        volumes:
        - ../../:/www

