blueprint: site
title: Site

tabs:
    content:
        icon: text
        label:
            en: Overview
            de: Übersicht
        columns:
            - width: 1/1
              sections:
                  caroussel:
                      extends: sections/home/caroussel
                      label:
                          en: Cover
                          de: Titelbilder
                      size: tiny

            - width: 1/3
                sections:                
                    listed_popup:
                        image: icon
                        type: pages
                        label: Popups
                        parent: site.find("home/popups")
                        status: listed
                        empty:
                            en: Currently no popup set
                            de: Aktuell ist kein Popup gesetzt
                        max: 1
                    draft_popup:
                        image: false
                        type: pages
                        label:
                            en: Draft
                            de: Entwürfe
                        empty:
                            en: No draft
                            de: kein Entwurf
                        parent: site.find("home/popups")
                        status: draft
                        max: 5

            - width: 1/3
blub
                    listed_speech:
                        type: pages
                        image: icon
                        label:
                            en: Speech
                            de: Ansprache
                        parent: site.find("home/ansprache")
                        status: listed
                        empty:
                            en: Currently no speech set!
                            de: Aktuell ist keine Ansprache gesetzt!
                        min: 1
                    draft_speech:
                        type: pages
                        image: false
                        label:
                            en: Draft
                            de: Entwürfe
                        empty:
                            en: No draft
                            de: kein Entwurf
                        parent: site.find("home/ansprache")
                        status: draft
                        templates: speech
                        max: 5

            - width: 1/3
                sections:
                    pages_dates:
                        type: pages
                        label:
                            en: Dates
                            de: Anstehende Termine
                        layout: list
                        image: icon
                        parent: site.find("dates")
                        status: listed

            - width: 1/3
                sections:
                    pages_active:
                        type: pages
                        label:
                            en: Linked Pages
                            de: Verlinkte Unterseiten
                        layout: list
                        image: false
                        status: listed

            - width: 1/3
                sections:
                    pages_unlisted:
                        type: pages
                        label:
                            en: Additional Pages
                            de: Sonstige Seiten
                        layout: list
                        image: false
                        sortBy: title desc
                        template:
                            - home
                            - footer
                            - error

            - width: 2/4
                sections:   
                    facebook:
                        type: fields
                        fields:
                            facebook:
                                label: Facebook Link
                                type: url
                            support:
                                label: Support
                                type: users
                                query: kirby.users.filterBy("support","true")
                                disabled: kirby.user.isAdmin

    seotab: seo

    technical:
        label:
            en: Technical
            de: Technisch
        columns:
            - width: 2/3
                sections:
                    pages_all:
                        type: pages
                        label:
                            en: All Pages
                            de: Alle Seiten

            - width: 1/3
                sections:
                    site_files:
                        type: files
                        label:
                            en: Files
                            de: Dateien
                        layout: list
                        image: icon

            - width: 1/4
                sections:
                    logo:
                        type: fields
                        fields:
                            logo:
                                label: Logo
                                type: files
                                min: 1
                                max: 1
                                multiple: false
                                layout: cards
                                query: site.images
                                image:
                                    back: white

            - width: 1/4
                sections:
                    logo_text:
                        type: fields
                        fields:
                            logotext:
                                label: Logotext
                                type: textarea

            - width: 2/4
                sections:
                    copyright:
                        type: fields
                        fields:
                            copyright:
                                label: Copyright
                                type: text
