blueprint: site
title: GCV 1962

tabs:
    content:
        icon: text
        label: 
            en: Overview
            de: Übersicht
        columns:
            - width: 1/1
              sections:
                  caroussel:
                      extends: sections/home/caroussel
                      label:
                          en: Cover
                          de: Titelbilder
                      size: tiny

            - width: 1/3
                sections:                
                    listed_popup:
                        image: icon
                        type: pages
                        label: Popups
                        parent: site.find("home/popups")
                        status: listed
                        empty:
                            en: Currently no popup set
                            de: Aktuell ist kein Popup gesetzt
                    draft_popup:
                        image: false
                        type: pages
                        label:
                            en: Draft
                            de: Entwürfe
                        parent: site.find("home/popups")
                        status: draft

            - width: 1/3
                sections:                
                    listed_speech:
                        type: pages
                        image: icon
                        label: 
                            en: Speech
                            de: Ansprache
                        parent: site.find("home/ansprache")
                        status: listed
                        empty:
                            en: Currently no popup set
                            de: Aktuell ist kein Popup gesetzt
                    draft_speech:
                        type: pages
                        image: false
                        label: 
                            en: Draft
                            de: Entwürfe
                        parent: site.find("home/ansprache")
                        status: draft

            - width: 1/3
                sections:
                    pages_dates:
                        type: pages
                        label:
                            en: Dates
                            de: Anstehende Termine
                        layout: list
                        image: icon
                        parent: site.find("dates")
                        status: listed
                
            - width: 1/2
                sections:
                    pages_active:
                        type: pages
                        label:
                            en: Linked Pages
                            de: Verlinkte Unterseiten
                        layout: list
                        image: false
                        status: listed

            - width: 1/2
                sections:
                    pages_unlisted:
                        type: pages
                        label:
                            en: Additional Pages
                            de: Sonstige Seiten
                        layout: list
                        image: false
                        status: unlisted
            
            - width: 1/4
                sections:
                    logo:
                        type: fields
                        fields:
                            logotext:
                                label: Logotext
                                type: textarea

            - width: 2/4
                sections:       
                    facebook:
                        type: fields
                        fields:
                            facebook:
                                label: Facebook
                                type: url
            
            - width: 1/4
                sections:       
                    support:
                        type: fields
                        fields:
                            support:
                                label: Support
                                type: users
                                query: kirby.users.filterBy("support","true")
                                disabled: kirby.user.isAdmin
              
    
    central:
        label: 
            en: Dontent
            de: Inhalt
        sections:
          pages_all:
            type: pages
            label: 
                en: All Pages
                de: Alle Seiten

    seotab: seo
