blueprint: site
title: GCV 1962

tabs:
    content:
        icon: text
        label: Content
        columns:
            - width: 1/1
              sections:
                  caroussel:
                      extends: sections/home/caroussel
                      label:
                          en: Cover
                          de: Titelbilder
                      size: tiny

            - width: 1/3
                sections:                
                    listed-popup:
                        image: icon
                        type: pages
                        label: Popups
                        parent: site.find("home/popups")
                        status: listed
                        info:
                            en: Currently no popup set
                            de: Aktuell ist kein Popup gesetzt
                    draft-popup:
                        image: false
                        type: pages
                        label:
                            en: Draft
                            de: Entwürfe
                        parent: site.find("home/popups")
                        status: draft

            - width: 1/3
                sections:                
                    listed-speech:
                        type: pages
                        image: icon
                        label: 
                            en: Speech
                            de: Ansprache
                        parent: site.find("home/ansprache")
                        status: listed
                    draft-speech:
                        type: pages
                        image: false
                        label: 
                            en: Draft
                            de: Entwürfe
                        parent: site.find("home/ansprache")
                        status: draft
            - width: 1/3
                sections:                
                    unlisted-pages:
                        type: pages
                        image: icon
                        label: 
                            en: Speech
                            de: Ansprache
                        parent: site.find("home/ansprache")
                        status: listed

            - width: 1/2
            - width: 1/2
              sections:
                  logo:
                      type: fields
                      fields:
                          logotext:
                              label: Logotext
                              type: textarea
                          facebook:
                              label: Facebook
                              type: url
                  support:
                      type: fields
                      fields:
                          support:
                              label: Support
                              type: users
                              query: kirby.users.filterBy("support","true")
                              disabled: kirby.user.isAdmin

    seotab: seo
