name: Deploy

on:
  push:
    branches: [ continious_delivery ]

jobs:
  webpage-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache packages
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/vendor
          ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - name: npm install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      #run: npm test
