name: Deploy

on:
  push:
    branches: [ continious_delivery ]

jobs:
  webpage-build:

    runs-on: ubuntu-latest
    env:
        TARGET_DIR: gcv1962_${{ GITHUB_RUN_ID }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CONTENTTOKEN }}
        submodules: 'true'

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache packages
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ./kirby
          ./vendor
          ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        restore-keys:
          ${{ runner.os }}-

    - name: composer install
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: npm install
      #if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      #run: npm test

    - name: Copy
      run: |
        mkdir "${TARGET_DIR}"
        rsync -av --exclude-from=deploy/dev/rsync.ignore --exclude "${TARGET_DIR}" . "${TARGET_DIR}"\
      
    - name: Publish
      env:
        DEPLOY_KEY: ${{ secrets.SERVERKEY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      run: |
        mkdir ~/.ssh
        echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 644 ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        scp -C -r "${TARGET_DIR}" ftp273539-2688012@webhosting78.1blu.de:www/"${TARGET_DIR}"
